# Generated by Django 6.0.7 on 2026-07-18 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import vault.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password", vault.fields.EncryptedCharField()),
                ("url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("social", "Social"),
                            ("banking", "Banking"),
                            ("work", "Work"),
                            ("email", "Email"),
                            ("shopping", "Shopping"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_favorite", "title"],
            },
        ),
    ]
