# Generated by Django 6.0.7 on 2026-07-18 06:51

from django.db import migrations

import vault.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaultentry",
            name="notes",
            field=vault.fields.EncryptedCharField(blank=True, default=""),
        ),
    ]
